services:
  app:
    container_name: smart-shell-mongo
    env_file:
      - ./.env
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - /var/www/volumes/smart-shell/smart-shell-mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_DATABASE
    networks:
      - smart-shell-net
    restart: unless-stopped

networks:
  smart-shell-net:
    external: true