services:
  app:
    container_name: smart-shell-mongo
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $SMART_SHELL_MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $SMART_SHELL_MONGO_PASSWORD
      MONGO_INITDB_DATABASE: $SMART_SHELL_MONGO_DATABASE
    ports:
      - "${SMART_SHELL_MONGO_PORT}:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - smart-shell-net
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  smart-shell-net:
    external: true